name: GitHub Actions
on: 
  push:

jobs:
  RunHugo:
    name: Generate static files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.16
      - name: install hugo
        run: snap install hugo --channel=extended
      - name: run hugo binary
        run: hugo -D
        working-directory: ${{ github.workspace }}/mysite
      - name: git setting
        run: |
          git config user.name actions-user
          git config user.email action@github.com
      - name: Commit files
        run: |
          git add -A
          if ! git diff-index --quiet HEAD --; then git commit -a -m "Generate static files (By GitHub Actions)"; fi;
          git push
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
